# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'ac388d23-a1f9-4b05-a70a-caf2a04c9ab8'
  imageRepository: 'rajeshmcloudnativeapp'
  containerRegistry: 'devopsdemodcr.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'devopsdemodcrd838-auth'

  

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  

stages:

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
   - job: HelmInstall
     displayName: HelmInstall

     pool:
      vmImage: $(vmImageName)
     steps:
     - task: HelmDeploy@0
       inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'Visual Studio Enterprise Subscription(bc96fb25-0001-4aeb-a9b7-4b49f30c94f5)'
        azureResourceGroup: 'myResourceGroup'
        kubernetesCluster: 'myAKSCluster'
        command: 'repo'
        arguments: 'add svc-cat https://svc-catalog-charts.storage.googleapis.com'
     - task: HelmDeploy@0
       inputs:
         connectionType: 'Azure Resource Manager'
         azureSubscription: 'Visual Studio Enterprise Subscription(1)(bc96fb25-0001-4aeb-a9b7-4b49f30c94f5)'
         azureResourceGroup: 'myResourceGroup'
         kubernetesCluster: 'myAKSCluster'
         namespace: 'default'
         command: 'helm update stable/nginx-ingress, helm install'
         #command: 'helm install'
         chartType: 'Name'
         chartName: 'stable/nginx-ingress'
         overrideValues: 'test=shubhasis'
         
     